In [2]:
import numpy as np
a1d = np.array ([5,6,7])
a2d = np.array ([[1,2,3],
                 [8,9,10]])
a3d= np.array([[17,18,19],
                 [14,15,16],
                [11,12,13]])                 

In [3]:
a1d, a2d, a3d

(array([5, 6, 7]),
 array([[ 1,  2,  3],
        [ 8,  9, 10]]),
 array([[17, 18, 19],
        [14, 15, 16],
        [11, 12, 13]]))

In [7]:
a1d.shape , a1d.ndim, a1d.dtype, a1d.size, type(a1d)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [10]:
a2d.shape , a2d.ndim, a2d.dtype, a2d.size, type(a2d)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [9]:
a3d.shape , a3d.ndim, a3d.dtype, a3d.size, type(a3d)

((3, 3), 2, dtype('int64'), 9, numpy.ndarray)

In [16]:
## Creating a dataframe out of numpy array 
## pd.DataFrame(data=None, index=None, columns=None)
import pandas as pd
datf_a2d = pd.DataFrame(data=a2d, index=['row1', 'row2'], columns=['col1','col2','col3'])

In [12]:
pip install pandas

     |████████████████████████████████| 9.7 MB 106 kB/s  eta 0:00:01
     |████████████████████████████████| 510 kB 11.4 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [17]:
datf_a2d

col1  col2  col3
row1     1     2     3
row2     8     9    10

In [18]:
a2d_ones = np.ones((10,2),dtype=int)

In [19]:
a2d_ones

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [20]:
rand_arr= np.arange(0,100,3)

In [21]:
rand_arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])